version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

defaults: &defaults
  docker:
    - image: circleci/node

step_install_deps: &install_deps
  run:
    name: Install Dependencies
    command: yarn

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - *install_deps
      - run: yarn test --ci
      - store_artifacts:
          path: coverage
      - codecov/upload:
          file: coverage/lcov.info

workflows:
  ci:
    jobs:
      - test:
          context:
            - test
